FROM nvcr.io/nvidia/pytorch:23.06-py3

RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y \
  libsndfile1 sox \
  libfreetype6 \
  swig \
  ffmpeg \
  libavdevice-dev && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /workspace/

# install megatron core, this can be removed once 0.3 pip package is released
RUN git clone https://github.com/NVIDIA/Megatron-LM.git && \
  cd Megatron-LM && \
  git checkout f24fac4ed0dcf0522056521a93445d9a82f501a9 && \
  pip install -e .

# install nemo dependencies
# WORKDIR /tmp/nemo
# COPY requirements .
# RUN for f in $(ls requirements*.txt); do pip3 install --disable-pip-version-check --no-cache-dir -r $f; done

COPY requirements .
RUN pip install -r requirements.txt
RUN pip install -r requirements_nlp.txt
RUN pip install -r requirements_test.txt
RUN pip install -r requirements_common.txt
RUN pip install -r requirements_lightning.txt
